
export const GET_FROM_API_SUCCESS="GET_FROM_API_SUCCESS";
export const GET_FROM_API_ERROR="GET_FROM_API_ERROR";
export const POST_RESPONSE_SUCCESS="POST_RESPONSE_SUCCESS";
export const PATCH_RESPONSE_SUCCESS="PATCH_RESPONSE_SUCCESS";
export const DELETE_RESPONSE_SUCCESS="DELETE_RESPONSE_SUCCESS"