//GET 
export const GET_REQ_ACTION="GET_REQ_ACTION"
export const GET_RES_SUCCESS="GET_RES_SUCCESS"
export const GET_RES_ERROR="GET_RES_ERROR"

//POST
export const POST_REQ_ACTION="POST_REQ_ACTION"
export const POST_RES_SUCCESS="POST_RES_SUCCESS"
export const POST_RES_ERROR="POST_RES_ERROR"
